name: Build
run-name: Build for ${{ github.ref_name }} by ${{ github.actor }}
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build ${{ matrix.package }} on ${{ matrix.system }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        system:
          - aarch64-darwin
          - aarch64-linux
          - x86_64-darwin
          - x86_64-linux
        package:
          - nightly
          - stable
        include:
          - system: aarch64-darwin
            runner: macos-14
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
          - system: x86_64-darwin
            runner: macos-15-intel
          - system: x86_64-linux
            runner: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Nix
        uses: cachix/install-nix-action@v31
      - name: Set up Cachix
        uses: cachix/cachix-action@v16
        with:
          name: heitor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build flake package
        run: nix build .#${{ matrix.package }} --accept-flake-config
